apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/spring-test-app.yaml
    - ./groups/default-org.yaml
    - ./systems/spring-test-app-system.yaml
    - ./domains/spring-test-app-domain.yaml
